//   Fatum -- Metadata Processing Library
//
//   Copyright (C) 2003-2023 Eric Knight
//   This software is distributed under the GNU Public v3 License
//
//   This program is free software: you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.

//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.

//   You should have received a copy of the GNU General Public License
//   along with this program.  If not, see <https://www.gnu.org/licenses/>.

using System.Collections;

namespace Proliferation.Fatum
{
    public sealed class AutoSchema
    {
        public Tree Schema = null;

        public AutoSchema(Tree DB)
        {
            Schema = new Tree();

            ArrayList fields = new ArrayList();
            recurseSchema(DB, fields);

            for (int i = 0; i < fields.Count; i++)
            {
                Tree newField = new Tree();
                newField.addElement("FieldName", (string)fields[i]);
                newField.addElement("FieldType", "String");
                newField.addElement("Description", "Autogenerated");
                Schema.addNode(newField, "Field");
            }
            fields.Clear();
        }

        ~AutoSchema()
        {
            if (Schema!=null)
            {
                Schema.dispose();
                Schema = null;
            }
        }

        private void recurseSchema(Tree currentNode, ArrayList fields)
        {
            if (currentNode != null)
            {
                int currentNodetreeCount = currentNode.tree.Count;

                for (int i = 0; i < currentNodetreeCount; i++)
                {
                    string currentLeafname = (string)currentNode.leafnames[i];
                    Tree currentTree = (Tree)currentNode.tree[i];

                    // Tricky logic- if the "value" of the Tree is not being used in the tuple,
                    //               we skip creating a column (these will appear as blanks)

                    if (currentTree.leafnames.Count == 0)
                    {
                        if (!isField(currentLeafname, fields))
                        {
                            if (!fields.Contains(currentLeafname))
                            {
                                if (!currentTree.Value.Equals(""))
                                {
                                    fields.Add(currentLeafname);
                                }
                            }
                        }
                    }
                    recurseSchema((Tree)currentNode.tree[i], fields);
                }
            }
        }

        private Boolean isField(String field, ArrayList fields)
        {
            Boolean found = false;

            int fieldsCount = 0;

            for (int i = 0; i < fieldsCount; i++)
            {
                String currentField = (string)fields[i];
                if (currentField.Equals(field))
                {
                    i = fieldsCount;
                    found = true;
                }
            }
            return found;
        }
    }
}
